"""add index to entry column

Revision ID: aeae6d900dae
Revises: 
Create Date: 2025-09-21 13:19:17.751109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeae6d900dae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_producer_entry'), 'producer', ['entry'], unique=False)
    op.create_index(op.f('ix_song_entry'), 'song', ['entry'], unique=False)
    op.create_index(op.f('ix_vocal_entry'), 'vocal', ['entry'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocal_entry'), table_name='vocal')
    op.drop_index(op.f('ix_song_entry'), table_name='song')
    op.drop_index(op.f('ix_producer_entry'), table_name='producer')
    # ### end Alembic commands ###
