"""song description nullable

Revision ID: c99f8ef155c6
Revises: 627370c2ba04
Create Date: 2025-09-21 18:34:06.519412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99f8ef155c6'
down_revision: Union[str, Sequence[str], None] = '627370c2ba04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producer_song', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='简介，用HTML格式写')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producer_song', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='简介，用HTML格式写')
    # ### end Alembic commands ###
