"""add producer_song image

Revision ID: ca66a612a51e
Revises: c99f8ef155c6
Create Date: 2025-09-25 10:33:30.669942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca66a612a51e'
down_revision: Union[str, Sequence[str], None] = 'c99f8ef155c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producer_song', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producer_song', 'image')
    # ### end Alembic commands ###
